export const ACTIONTYPE = { 
    CHANGE_STEPPER: 'CHANGE_STEPPER', 
    SUBMIT_DATA_ONE_REQUEST: 'SUBMIT_FORM_ONE_REQUEST',
    SUBMIT_DATA_ONE_SUCCESS: 'SUBMIT_FORM_ONE_SUCCESS',
    SUBMIT_DATA_ONE_FAILURE: 'SUBMIT_FORM_ONE_FAILURE',
    SUBMIT_DATA_TWO: 'SUBMIT_FORM_TWO'
}